language: node_js
node_js:
    - "6"
addons:
  sauce_connect: true
services:
  - docker
sudo: required
install:
  - cd server && npm install
  - cd website && npm install
before_script:
  - docker build -t ilkkao/mas-travis .
script:
  - cd server && npm test
