language: node_js
node_js:
    - "6"
addons:
  sauce_connect: true
services:
  - docker
sudo: required
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - cd server && yarn && cd ..
  - cd server/website && yarn && cd ../..
  - cd server/test/browser && yarn && cd ../../..
script:
  - cd server && npm test
