language: node_js
node_js:
    - "9"
addons:
  sauce_connect: true
services:
  - docker
sudo: required
cache:
  directories:
  - $HOME/.yarn-cache
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - PATH="$HOME/.yarn/bin:$PATH"
  - cd server && yarn && cd ..
  - cd website && yarn && cd ..
  - cd server/test/browser && yarn && cd ../../..
script:
  - yarn install
  - yarn run lint-server
  - yarn run lint-client
  - cd server && yarn test
