language: node_js
node_js:
    - "6"
addons:
  sauce_connect: true
services:
  - docker
sudo: required
before_install:
  - docker build -t ilkkao/mas-travis .
  - sudo apt-get install ircd-irc2
  - sudo /etc/init.d/ircd-irc2 start
script:
  - cd server && npm test
