language: node_js
node_js:
    - "6"
addons:
  sauce_connect: true
services:
  - docker
sudo: required
install:
  - cd server && npm install && cd ..
  - cd server/website && npm install && cd ../..
  - cd server/test/browser && npm install && cd ../../..
script:
  - cd server && npm test
