language: node_js

env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH

node_js:
  - "0.11"

cache:
  directories:
      - node_modules

before_install:
  - npm config set loglevel warn --global
  - npm install -g casperjs
  - npm install -g gulp
  - sudo apt-get install ircd-irc2
  - sudo /etc/init.d/ircd-irc2 start

before_script:
  - casperjs --version
  - ./bin/travis-install-slimerjs.sh
