version: '3'
services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.23'
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'
    volumes:
      - ./mas-development/es:/usr/share/elasticsearch/data
  redis:
    image: 'redis:6.2.3'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 600 1 --save 300 10 --save 60 10000
    volumes:
      - ./mas-development/redis:/data
  nginx:
    image: 'nginx:1.13.6'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./nginx.conf.dev:/etc/nginx/nginx.conf:ro
