volumes:
  mas-data:
  mas-elasticsearch-data:
  mas-redis-data:
services:
  mas-frontend:
    image: 'mas:latest'
    build: .
    ports:
      - '80:3200'
      - '443:3201'
    volumes:
      - mas-data:/data
  mas-loopback:
    image: 'mas:latest'
    build: .
    volumes:
      - mas-data:/data
  mas-irc:
    image: 'mas:latest'
    build: .
    volumes:
      - mas-data:/data
  mas-irc-scktmgr:
    image: 'mas:latest'
    build: .
    volumes:
      - mas-data:/data
  elasticsearch:
    volumes:
      - mas-elasticsearch-data:/usr/share/elasticsearch/data
  elasticsearch-head:
  redis:
    volumes:
      - mas-redis-data:/data
