version: '3'
services:
  mas-frontend:
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment: &app-environment
      NODE_ENV: production
      PROJECT_ROOT: /app/
      FILES__UPLOAD_DIRECTORY: /data/mas/uploads/
      FILES__CACHE_DIRECTORY: /data/mas/cache/
      FILES__AUTOROTATE_JPEGS: 'true'
      REDIS__HOST: redis
      ELASTICSEARCH__ENABLED: 'true'
      ELASTICSEARCH__HOST: elasticsearch
    command: yarn run start-frontend
  mas-loopback:
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      <<: *app-environment
    command: yarn run start-loopback
  mas-irc:
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      <<: *app-environment
    command: yarn run start-irc
  mas-irc-scktmgr:
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      <<: *app-environment
    command: yarn run start-irc-scktmgr
    ports:
      - '113:113'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.13'
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.ml.enabled=false
    ports:
      - '127.0.0.1:9200:9200'
      - '127.0.0.1:9300:9300'
  elasticsearch-head:
    image: 'mobz/elasticsearch-head:5'
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '127.0.0.1:9100:9100'
  redis:
    image: 'redis:6.2.1'
    restart: always
    ports:
      - '127.0.0.1:6379:6379'
    command: redis-server --save 600 1 --save 300 10 --save 60 10000
