version: '2'
services:
  mas-frontend:
    image: 'ilkkao/mas:latest'
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - LOG__CONSOLE=true
      - LOG__DIRECTORY=/data/logs/
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    ports:
      - '80:3200'
      - '443:3201'
    volumes:
      - /data:/data
  mas-loopback:
    image: 'ilkkao/mas:latest'
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - LOG__CONSOLE=true
      - LOG__DIRECTORY=/data/logs/
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: npm run start-loopback
    volumes:
      - /data:/data
  mas-irc:
    image: 'ilkkao/mas:latest'
    depends_on:
      - elasticsearch
      - redis
    restart: always
    environment:
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - LOG__CONSOLE=true
      - LOG__DIRECTORY=/data/logs/
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: npm run start-irc
    volumes:
      - /data:/data
  mas-irc-scktmgr:
    image: 'ilkkao/mas:latest'
    depends_on:
      - elasticsearch
      - redis
    environment:
      - FILES__UPLOAD_DIRECTORY=/data/uploads/
      - FILES__CACHE_DIRECTORY=/data/cache/
      - FILES__AUTOROTATE_JPEGS=true
      - LOG__CONSOLE=true
      - LOG__DIRECTORY=/data/logs/
      - REDIS__HOST=redis
      - ELASTICSEARCH__ENABLED=true
      - ELASTICSEARCH__HOST=elasticsearch
    command: npm run start-irc-scktmgr
    volumes:
      - /data:/data
    ports:
      - '113:113'
  elasticsearch:
    image: 'elasticsearch:5.1.1'
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
  redis:
    image: 'redis:latest'
    volumes:
      - /data/redis:/data
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes --save 600 1 --save 300 10 --save 60 10000
