name: Build and publish docker image

on:
  push:
    branches: master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mas:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
